pipeline {
    agent { label 'Tuan'}  // This is the name of the agent defined in Jenkins configuration
    stages {
        stage("Hello World") {
            steps {
                echo "Hello World"
            }
        }

        stage('Run Batch Script 1') {
            steps {
                echo 'Running Batch Script 1...'
                bat 'Script/Batch_script_1.bat'
            }
        }

        stage('Run Batch Script 2') {
            when {
                expression { currentBuild.result == 'FAILURE' }
            }
            steps {
                echo 'Running Batch Script 2 due to failure in previous stage...'
                bat 'Script/Batch_script_2.bat'
            }
        }

        stage('Run Batch Script 3') {
            steps {
                echo 'Running Batch Script 3 (always runs, regardless of build status)...'
                bat 'Script/Batch_script_3.bat'
            }
        }
    }

    // post {
    //     always {
    //         echo 'Archiving log file generated by Batch Script 3...'
    //         archiveArtifacts artifacts: '.\\Script\\Test\\logfile.log', fingerprint: true
    //     }
    // }
}
