pipeline {
    agent { label 'Tuan' }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage("Hello World") {
            steps {
                echo "Hello World"
            }
        }

        stage('Run Batch Script 1') {
            steps {
                echo 'Running Batch Script 1...'
                bat 'Script/Batch_script_1.bat'
            }
        }

        stage('Run Batch Script 3') {
            steps {
                echo 'Running Batch Script 3 (always runs, regardless of build status)...'
                bat 'Script/Batch_script_3.bat'
            }
        }

        stage('Check Logfile') {
            steps {
                echo 'Checking logfile content...'
                bat 'type D:\\code\\test\\workspace\\or_test_test_executing_file_main\\Script\\logfile.log'
            }
        }
    }

    post {
        always {
            echo 'Archiving log file generated by Batch Script 3...'
            archiveArtifacts artifacts: 'D:\\code\\test\\workspace\\or_test_test_executing_file_main\\Script\\logfile.log', fingerprint: true
        }
        cleanup {
            cleanWs()
        }
    }
}
