pipeline {
    agent { label 'Tuan' }

    stages {
        stage("Hello World") {
            steps {
                echo "Hello World"
            }
        }

        stage('Run Batch Script 1') {
            steps {
                script {
                    echo 'Running Batch Script 1...'
                    def result = catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        bat 'Script/Batch_script_1.bat'
                    }
                    echo "Stage 1 Result: ${result}"
                }
            }
        }

        stage('Run Batch Script 2') {
            when {
                expression { return currentBuild.getResult().toString() == 'FAILURE' }
            }
            steps {
                echo 'Running Batch Script 2 due to failure in previous stage...'
                bat 'Script/Batch_script_2.bat'
            }
        }

        stage('Run Batch Script 3') {
            steps {
                echo 'Running Batch Script 3 (always runs, regardless of build status)...'
                bat 'Script/Batch_script_3.bat'
                echo 'Archiving log file generated by Batch Script 3...'
                archiveArtifacts artifacts: 'Script/logfile.log', fingerprint: true
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}
